### ISSUE TITLE
How can I apply to multi layers model?

### ISSUE THREAD

**Issue by Ryoga723** [moof2k/kerasify#13]
Hello,I have two question.

1.I 'd like to improve processing speed with my model which include LSTM layer and Dense layer.
But when I export model, this error occurs.

File "/home/kerasify-master/kerasify.py", line 139, in export_model
    b_c = weights[3]
IndexError: list index out of range

My model's structure is like below.
model = Sequential()
model.add(LSTM(n_hidden, input_shape=(trainX.shape[1], look_back)))
model.add(Dense(2))
model.add(Activation("linear"))
model.compile(loss='mean_squared_error', optimizer='adam')

Is there anything to note when I apply to multi layer model?

2.When I execute cpp program which contain  KerasModel model , it doesn't work well. And this error occurs.

undefined reference to `vtable for KerasModel' 

Is there other way to get model ?

Thank you for your help.

**Comment by insunkang** [comment]
i have similar question.

model = Sequential()
model.add(LSTM(10, activation = 'relu', input_shape=(3,1)))
model.add(Dense(5))
model.add(Dense(1))

want to use this kind of model but,

there is some error like,
 inner_activation = layer.get_config()['inner_activation']
KeyError: 'inner_activation' 
or
 W_c = weights[3]
IndexError: list index out of range

Thank you.

**Comment by Ryoga723** [comment]
I'm sorry to be late for reply.
After changing python version, I have same error as you at all.

This is my solution.
1.To replace inner_activation to recurrent_activation.
2.To change trainable weights description like below.
W = layer.get_weights()[0]
                U = layer.get_weights()[1]
                b = layer.get_weights()[2]

                units = n_hidden

                W_i = W[:, :units]
                W_f = W[:, units: units * 2]
                W_c = W[:, units * 2: units * 3]
                W_o = W[:, units * 3:]

                U_i = U[:, :units]
                U_f = U[:, units: units * 2]
                U_c = U[:, units * 2: units * 3]
                U_o = U[:, units * 3:]

                b_i = b[:units]
                b_f = b[units: units * 2]
                b_c = b[units * 2: units * 3]
                b_o = b[units * 3:]

in kerasify.py.



Thank you.
