### ISSUE TITLE
Adding LSTM layers

### ISSUE THREAD

**Issue by danieleghisi** [moof2k/kerasify#2]
Hi, 
thanks for sharing this, really helpful. I was wondering if there were any plans to add support for LSTM layers... 
Thanks!
daniele

**Comment by ddovod** [comment]
+1 for lstm! Really useful thing. Thank you a lot!

**Comment by javierfvargas** [comment]
#3

**Comment by moof2k** [comment]
Thanks @javierfvargas ! PR integrated
