### ISSUE TITLE
Kerasify work with Keras 2.0.5?

### ISSUE THREAD

**Issue by giovanniluccasilva** [moof2k/kerasify#8]

**Comment by davideboschetto** [comment]
To be able to use it with Keras 2.0, you need to rename "Convolution2D" to "Conv2D", "border_mode" to "padding", and generally all the changes that are listed [here in the release notes](https://github.com/fchollet/keras/wiki/Keras-2.0-release-notes)

**Comment by giovanniluccasilva** [comment]
thank you
